text="chersétudiantsdelaclasseran1aujourdhuinousvoulonsvousrappeleràquelpointvousêtesexceptionnelsvousavezentreprisunvoyagepassionnantverslemondedelaprogrammationetvousavezdéjàparcouruunegrandepartieducheminlesdéfisquiseprésententàvouspeuventsemblerintimidantsmaisnoubliezjamaisquevousavezlepouvoirdelessurmonterlaprogrammationnestpasseulementunensembledecompétencestechniquescestuneformedartchaquelignedecodequevousécrivezestuneœuvredartensoiuneexpressiondevotrecréativitéetdevotreingéniositévousavezlepotentieldecréerdesapplicationsdessiteswebetdeslogicielsquichangerontlemondenayezpaspeurdeserreurscarcesontleserreursquivousfontgrandirchaquebugquevouscorrigezchaqueproblèmequevousrésolvezvousrapprochedelamaîtrisedecettedisciplinecomplexelesdifficultésnesontquedesopportunitésdéguiséespourapprendreetgrandirnoubliezpasnonplusquevousnêtespasseulsdanscetteaventurevotreclasseestuneéquipeunecommunautédepersonnespartageantlamêmepassionetlesmêmesdéfisentravaillantensembleenpartageantvosconnaissancesetenvoussoutenantmutuellementvouspouvezaccomplirdeschosesincroyablesvousavezchoisiuncheminexigeantmaisaussiincroyablementgratifiantvousêteslescréateursdedemainlesconstructeursdufuturneperdezjamaisdevuevosrêvesetvosaspirationscontinuezàtravaillerduràrestercurieuxetàrepousservoslimitesnouscroyonsenvousetnoussommesimpatientsdevoirlesmerveillesquevouscréerezalorsenavantdéveloppeursran1!lemondeabesoindevotretalentdevotrepassionetdevotredéterminationvousêtescapablesdetoutetnoussommesfiersdevousaccompagnerdanscetteaventureextraordinaireboncourageetquelecodesoitavecvous!avectoutnotresoutienléquipemns"

#On demande la lettre à rechercher.

#Il faut parcourir chacune des lettre, et si on la trouve, on rajoute +1 à notre compteur.

compteur = 0

while True :
    try : 
        lettre_a_retrouver = str(input("Veuillez rentrer une lettre de l'alphabet. Une seule."))
        break
    except ValueError :
        print("Suis la consigne!")

for i in len(text):
    if text[i] == lettre_a_retrouver : 
        compteur = compteur + 1

print (f"La lettre à retrouver était {lettre_a_retrouver}, il y en as {compteur} dans le texte.")